/**
 * Where the built-in character artwork lives.
 *
 * Generated by `node scripts/make-character.mjs` — edit the painter in
 * `src/core/generators/skin/`, not this file. `path` is what a preset puts in
 * its `url`: relative to the app's base URL, and under `textures/` so the
 * preset validator accepts it.
 */

export interface CharacterTexture {
  /** Texture slot key on the entity node this PNG belongs in. */
  slot: string
  fileName: string
  /** App-relative path, for a preset's `url`. */
  path: string
  width: number
  height: number
  /** SHA-256 of the bytes, so a stale checkout is obvious rather than subtle. */
  digest: string
}

export const CHARACTER_TEXTURES: CharacterTexture[] = [
  { slot: 'main', fileName: 'kohane.png', path: 'textures/characters/kohane/kohane.png', width: 512, height: 512, digest: '46ba00b291e47d02' },
  { slot: 'spawn_egg', fileName: 'kohane_spawn_egg.png', path: 'textures/characters/kohane/kohane_spawn_egg.png', width: 128, height: 128, digest: 'e76273ed8e15ec02' },
]

/** The texture for one entity slot, or undefined if the build did not write it. */
export function characterTexture(slot: string): CharacterTexture | undefined {
  return CHARACTER_TEXTURES.find((texture) => texture.slot === slot)
}
