/**
 * The build files: loader metadata, Gradle scripts and the README that tells
 * you what to run.
 *
 * These are the least interesting files in the export and the most
 * unforgiving: a `mods.toml` with the wrong loader range or a `build.gradle`
 * missing the loader's own Maven repository fails before a single line of the
 * generated Java is compiled, and the error message rarely says which. So every
 * coordinate comes from the target profile — see `targets/javaProfiles.ts` —
 * rather than being written inline, and a new Minecraft version is a profile
 * entry rather than a search through template strings.
 */

import type { VirtualFile } from '../../vfs/types'
import type { ModLoader } from '../../targets/platforms'
import { LOADERS } from '../../targets/platforms'
import type { JavaContext } from './context'
import { loaderCode } from './loaderCode'
import { rootPackage } from './ids'

function text(path: string, value: string, label: string): VirtualFile {
  return { path, origin: { label }, body: { type: 'text', value } }
}

function json(path: string, value: unknown, label: string): VirtualFile {
  return { path, origin: { label }, body: { type: 'json', value } }
}

export function emitBuildFiles(
  ctx: JavaContext,
  loader: Exclude<ModLoader, 'datapack'>,
  mainClass: string,
): VirtualFile[] {
  const versions = ctx.profile.loaders[loader]
  if (!versions) {
    ctx.warn(
      `${LOADERS[loader].label} has no published coordinates for Minecraft ${ctx.profile.minecraftVersion}, so its build files were skipped.`,
    )
    return []
  }

  const files: VirtualFile[] = [
    emitGradleProperties(ctx, loader),
    emitSettingsGradle(ctx, loader),
    emitBuildGradle(ctx, loader),
    emitGitignore(),
    emitReadme(ctx, loader),
  ]

  files.push(...emitMetadata(ctx, loader, mainClass))
  return files
}

// -- gradle ------------------------------------------------------------------

function emitGradleProperties(ctx: JavaContext, loader: Exclude<ModLoader, 'datapack'>): VirtualFile {
  const versions = ctx.profile.loaders[loader]!
  const extra = Object.entries(versions.properties)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n')

  return text(
    'gradle.properties',
    `# Generated by the add-on builder. Bump a version here rather than in build.gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=${ctx.profile.minecraftVersion}
${extra}

mod_id=${ctx.modId}
mod_version=${ctx.project.version.join('.')}
maven_group=${rootPackage(ctx.project)}
archives_base_name=${ctx.modId}
`,
    'Gradle · properties',
  )
}

function emitSettingsGradle(ctx: JavaContext, loader: Exclude<ModLoader, 'datapack'>): VirtualFile {
  const versions = ctx.profile.loaders[loader]!
  // Every loader publishes its Gradle plugin to its own Maven, not to the
  // plugin portal, so the repository has to be declared before the plugin is
  // resolved — which is what pluginManagement is for.
  const repositories =
    loader === 'fabric' || loader === 'quilt'
      ? `        maven { url = 'https://maven.fabricmc.net/' }\n        gradlePluginPortal()`
      : `        gradlePluginPortal()\n        maven { url = '${versions.mavenUrl}' }`

  return text(
    'settings.gradle',
    `pluginManagement {
    repositories {
${repositories}
    }
}

rootProject.name = '${ctx.modId}'
`,
    'Gradle · settings',
  )
}

function emitBuildGradle(ctx: JavaContext, loader: Exclude<ModLoader, 'datapack'>): VirtualFile {
  const versions = ctx.profile.loaders[loader]!
  const java = ctx.profile.javaVersion
  const code = loaderCode(loader, ctx.profile)

  const common = `version = mod_version
group = maven_group

base {
    archivesName = archives_base_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(${java})
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = ${java}
}
`

  if (loader === 'fabric' || loader === 'quilt') {
    const quiltNote =
      loader === 'quilt'
        ? `
// Built with Fabric Loom on purpose. Quilt Loader reads quilt.mod.json natively
// and also understands Fabric mods, so one Loom build produces a jar that runs
// on both loaders instead of needing a separate Quilt toolchain.
`
        : ''

    return text(
      'build.gradle',
      `plugins {
    ${versions.gradlePlugin}
    id 'java'
}
${quiltNote}
${common}
repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:\${minecraft_version}"
    // Official Mojang mappings rather than Yarn, so the sources this builder
    // generates compile unchanged on every loader it targets.
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:\${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:\${fabric_version}"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mod_id', mod_id
    filesMatching(['fabric.mod.json', 'quilt.mod.json']) {
        expand version: project.version, mod_id: mod_id
    }
}
`,
      'Gradle · build',
    )
  }

  if (code.family === 'forge') {
    return text(
      'build.gradle',
      `plugins {
    ${versions.gradlePlugin}
    id 'java'
}

${common}
repositories {
    maven { url = '${versions.mavenUrl}' }
}

minecraft {
    // 'official' is Mojang's own mapping set, matching the Fabric build above.
    mappings channel: 'official', version: minecraft_version

    runs {
        client { workingDirectory project.file('run') }
        server { workingDirectory project.file('run') }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:\${minecraft_version}-\${forge_version}"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mod_id', mod_id
    filesMatching('META-INF/*.toml') {
        expand version: project.version, mod_id: mod_id
    }
}
`,
      'Gradle · build',
    )
  }

  return text(
    'build.gradle',
    `plugins {
    ${versions.gradlePlugin}
    id 'java'
}

${common}
repositories {
    maven { url = '${versions.mavenUrl}' }
}

neoForge {
    version = neoforge_version

    runs {
        client { client() }
        server { server() }
    }

    mods {
        "\${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mod_id', mod_id
    filesMatching('META-INF/*.toml') {
        expand version: project.version, mod_id: mod_id
    }
}
`,
    'Gradle · build',
  )
}

function emitGitignore(): VirtualFile {
  return text(
    '.gitignore',
    `.gradle/
build/
run/
.idea/
*.iml
out/
`,
    'Project · gitignore',
  )
}

// -- loader metadata ---------------------------------------------------------

function emitMetadata(
  ctx: JavaContext,
  loader: Exclude<ModLoader, 'datapack'>,
  mainClass: string,
): VirtualFile[] {
  const versions = ctx.profile.loaders[loader]!
  const author = ctx.project.meta.author || 'Unknown'
  const base = 'src/main/resources'

  if (loader === 'fabric' || loader === 'quilt') {
    const fabricJson = json(
      `${base}/fabric.mod.json`,
      {
        schemaVersion: 1,
        id: ctx.modId,
        version: '${version}',
        name: ctx.project.name,
        description: ctx.project.description || `${ctx.project.name}, built with the add-on builder.`,
        authors: [author],
        license: 'ARR',
        environment: '*',
        entrypoints: {
          main: [mainClass],
          client: [`${mainClass}Client`],
        },
        depends: {
          fabricloader: versions.loader,
          minecraft: `~${ctx.profile.minecraftVersion}`,
          java: `>=${ctx.profile.javaVersion}`,
          'fabric-api': versions.api ?? '*',
        },
      },
      'Fabric · mod metadata',
    )

    if (loader === 'fabric') return [fabricJson]

    // Quilt gets both files: quilt.mod.json is what Quilt Loader reads, and the
    // Fabric one alongside it means the same jar also runs on Fabric.
    return [
      fabricJson,
      json(
        `${base}/quilt.mod.json`,
        {
          schema_version: 1,
          quilt_loader: {
            group: rootPackage(ctx.project),
            id: ctx.modId,
            version: '${version}',
            metadata: {
              name: ctx.project.name,
              description:
                ctx.project.description || `${ctx.project.name}, built with the add-on builder.`,
              contributors: { Author: author },
              license: 'ARR',
            },
            intermediate_mappings: 'net.fabricmc:intermediary',
            entrypoints: {
              init: [mainClass],
              client_init: [`${mainClass}Client`],
            },
            depends: [
              { id: 'quilt_loader', versions: versions.loader },
              { id: 'minecraft', versions: `~${ctx.profile.minecraftVersion}` },
            ],
          },
        },
        'Quilt · mod metadata',
      ),
    ]
  }

  // Both Forge and NeoForge read a TOML file; only its name and the dependency
  // block's mod id differ, which is exactly what the profile records.
  const isNeo = loader === 'neoforge'
  const loaderMod = isNeo ? 'neoforge' : 'forge'
  const loaderRange = versions.loader

  return [
    text(
      `${base}/${versions.metadataPath}`,
      `# Generated by the add-on builder.
modLoader = "javafml"
loaderVersion = "${loaderRange}"
license = "All rights reserved"

[[mods]]
modId = "\${mod_id}"
version = "\${version}"
displayName = "${ctx.project.name}"
authors = "${author}"
description = '''
${ctx.project.description || `${ctx.project.name}, built with the add-on builder.`}
'''

[[dependencies.\${mod_id}]]
    modId = "${loaderMod}"
    type = "required"
    versionRange = "${loaderRange}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.\${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${ctx.profile.minecraftVersion}]"
    ordering = "NONE"
    side = "BOTH"
`,
      `${isNeo ? 'NeoForge' : 'Forge'} · mod metadata`,
    ),
  ]
}

// -- README ------------------------------------------------------------------

function emitReadme(ctx: JavaContext, loader: Exclude<ModLoader, 'datapack'>): VirtualFile {
  const info = LOADERS[loader]
  const versions = ctx.profile.loaders[loader]!

  return text(
    'README.md',
    `# ${ctx.project.name} — ${info.label} mod

Generated by the add-on builder from the same project that produces the Bedrock
\`.mcaddon\`. **This is a source project, not a finished mod.** Compiling Java
needs a JDK, which a browser tab does not have, so the last step is yours — and
it is one command.

## Build it

\`\`\`bash
gradle wrapper          # only the first time, to create ./gradlew
./gradlew build
\`\`\`

The jar lands in \`build/libs/\`. Drop it in your \`mods/\` folder alongside
${loader === 'fabric' || loader === 'quilt' ? '**Fabric API**' : `**${info.label}**`}.

Requires **Java ${ctx.profile.javaVersion}** and targets **Minecraft
${ctx.profile.minecraftVersion}** with ${info.label} \`${versions.loader}\`.

## What is generated, and what is yours

Everything under \`src/main/java\` and \`src/main/resources\` is regenerated on
every export, so **edits there are overwritten**. To add behaviour the builder
does not cover, put it in a new class and call it from the entry point — that
file is regenerated too, but a one-line call is trivial to re-add, whereas a
rewritten class is not.

| Path | What it is |
|---|---|
| \`src/main/java/\` | Registration, blocks, items, crops and any custom crafting stations |
| \`src/main/resources/data/\` | The data pack — recipes, loot, tags, world generation |
| \`src/main/resources/assets/\` | The resource pack — models, blockstates, textures, language |
| \`${versions.metadataPath}\` | Mod metadata, filled in by Gradle at build time |

## Mappings

Built against **official Mojang mappings** rather than Yarn, so the generated
sources are identical across all four loaders. If you are used to Yarn names,
\`Block#use\` and friends will look slightly different — that is the mapping,
not a different API.

## Known gaps

See \`docs/PLATFORMS.md\` in the builder for the full support matrix. The short
version for this export:

- Entities register but ship a placeholder renderer you have to fill in.
- Custom block shapes beyond a full block and a cross model are yours to write.
- Custom crafting stations are complete and use the vanilla crafting-table frame
  as their background; swap \`BACKGROUND\` in \`StationScreen\` for your own.
`,
    'Project · README',
  )
}
