/**
 * The Java source tree of an exported mod.
 *
 * This is the part of the builder that cannot pretend the two platforms are
 * alike. A Bedrock block is a JSON file the game reads; a Java block is an
 * object that has to be constructed and handed to a registry while the game is
 * starting, which means real code. So the export is a Gradle project rather
 * than a finished jar — a browser tab cannot run javac — and the honest promise
 * is "everything is written for you, run ./gradlew build".
 *
 * Two decisions keep this manageable:
 *
 *   **Mojang mappings everywhere.** Fabric is generated against
 *   `officialMojangMappings()` rather than Yarn, so one set of templates
 *   compiles on all four loaders instead of Fabric needing its own dialect of
 *   every class name.
 *
 *   **The loader differences are a short list, not a fork.** Registration is
 *   the only thing that genuinely differs — Fabric calls `Registry.register`
 *   directly, the Forge family uses a `DeferredRegister` — so that one method
 *   is written per loader and everything downstream is shared.
 *
 * Anything version-specific (a renamed method, a constructor that went private)
 * lives in the profile's `api` block, never inline here.
 */

import type { ContentNode } from '../../model/types'
import type { VirtualFile } from '../../vfs/types'
import { bool, list, num, str } from '../../kinds/shared'
import type { JavaContext } from './context'
import { constantCase, packagePath, pascalCase, rootPackage } from './ids'
import { isFabricFamily, loaderCode } from './loaderCode'
import type { LoaderCode } from './loaderCode'

function javaFile(pkg: string, className: string, body: string): VirtualFile {
  return {
    path: `src/main/java/${packagePath(pkg)}/${className}.java`,
    origin: { label: `Java · ${className}` },
    body: { type: 'text', value: body },
  }
}

/** Turns a string into a Java string literal, escaping what has to be escaped. */
function lit(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`
}

export interface SourceOutput {
  files: VirtualFile[]
  /** Fully qualified name of the mod's entry class, for the loader metadata. */
  mainClass: string
}

export function emitSources(ctx: JavaContext, stationBlocks: ContentNode[]): SourceOutput {
  const pkg = rootPackage(ctx.project)
  const files: VirtualFile[] = []
  const code = loaderCode(ctx.loader, ctx.profile)
  const fabric = isFabricFamily(ctx.loader)

  files.push(emitModMain(ctx, pkg, fabric, code))
  files.push(emitRegistryHelper(ctx, pkg, fabric, code))
  files.push(emitModItems(ctx, pkg, code))
  files.push(emitModBlocks(ctx, pkg, stationBlocks, code))
  files.push(emitCreativeTab(ctx, pkg, code))

  for (const node of ctx.project.nodes.filter((n) => n.kind === 'crop')) {
    files.push(emitCropBlock(pkg, node))
  }

  const structures = ctx.project.nodes.filter((n) => n.kind === 'structure')
  if (structures.length > 0) files.push(emitStructureFeature(ctx, pkg, structures))

  if (fabric) files.push(emitFabricWorldgen(ctx, pkg))

  return { files, mainClass: `${pkg}.${pascalCase(ctx.project.namespace)}Mod` }
}

// -- entry point -------------------------------------------------------------

function emitModMain(ctx: JavaContext, pkg: string, fabric: boolean, code: LoaderCode): VirtualFile {
  const className = `${pascalCase(ctx.project.namespace)}Mod`
  const hasStructures = ctx.project.nodes.some((n) => n.kind === 'structure')

  const body = fabric
    ? `package ${pkg};

import net.fabricmc.api.ModInitializer;

/**
 * Entry point. Fabric calls onInitialize once, on both client and server, after
 * the registries are open — which is why every registration below is a plain
 * static-initialiser touch rather than an event subscription.
 *
 * Generated by the add-on builder. Re-exporting overwrites this file, so put
 * hand-written code in a new class instead of editing this one.
 */
public class ${className} implements ModInitializer {
    public static final String MOD_ID = ${lit(ctx.modId)};

    @Override
    public void onInitialize() {
        ModItems.register();
        ModBlocks.register();
        ModCreativeTabs.register();
        ModStations.register();${hasStructures ? '\n        ModStructures.register();' : ''}
        ModWorldgen.register();
    }
}
`
    : (() => {
        const ctor = code.modConstructor(className)
        const annotation = code.family === 'forge' ? '@Mod' : '@Mod'
        return `package ${pkg};

${code.modImports.map((name) => `import ${name};`).join('\n')}

/**
 * Entry point. The Forge family constructs the mod class with the mod event
 * bus, and every DeferredRegister has to be attached to it here — a register
 * that is never attached simply never fires, with no error to notice.
 *
 * Generated by the add-on builder. Re-exporting overwrites this file, so put
 * hand-written code in a new class instead of editing this one.
 */
${annotation}(${className}.MOD_ID)
public class ${className} {
    public static final String MOD_ID = ${lit(ctx.modId)};

    ${ctor.signature} {
        ${ctor.busExpression}
        ModItems.REGISTER.register(modBus);
        ModBlocks.REGISTER.register(modBus);
        ModCreativeTabs.REGISTER.register(modBus);
        ModStations.MENUS.register(modBus);${hasStructures ? '\n        ModStructures.FEATURES.register(modBus);' : ''}
    }
}
`
      })()

  return javaFile(pkg, className, body)
}

/**
 * One place that knows how this loader registers things.
 *
 * Fabric hands you the vanilla registries directly; the Forge family insists on
 * a DeferredRegister so entries are created at the right moment in startup.
 * Both are wrapped in the same two-method surface so the callers below read
 * identically whichever loader they were generated for.
 */
function emitRegistryHelper(ctx: JavaContext, pkg: string, fabric: boolean, code: LoaderCode): VirtualFile {
  const rl = ctx.profile.api.resourceLocation('MOD_ID', 'path')
  const modClass = `${pascalCase(ctx.project.namespace)}Mod`

  const body = fabric
    ? `package ${pkg};

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;

import java.util.function.Supplier;

/**
 * Registration, Fabric flavour.
 *
 * The Supplier returned here is immediate rather than deferred — Fabric has
 * already opened the registries by the time onInitialize runs — but it keeps the
 * call sites identical to the Forge build, which is the whole point.
 */
public final class ModRegistry {
    public static final String MOD_ID = ${modClass}.MOD_ID;

    private ModRegistry() {}

    public static ResourceLocation id(String path) {
        return ${rl};
    }

    public static Supplier<Item> item(String path, Supplier<Item> factory) {
        Item registered = Registry.register(BuiltInRegistries.ITEM, id(path), factory.get());
        return () -> registered;
    }

    public static Supplier<Block> block(String path, Supplier<Block> factory) {
        Block registered = Registry.register(BuiltInRegistries.BLOCK, id(path), factory.get());
        return () -> registered;
    }
}
`
    : `package ${pkg};

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
${code.registryImports.map((name) => `import ${name};`).join('\n')}

import java.util.function.Supplier;

/**
 * Registration, Forge-family flavour.
 *
 * DeferredRegister exists because the Forge family constructs mods before the
 * registries are open, so an entry created eagerly would be created too early.
 * Every register in this class is attached to the mod bus in ${modClass}.
 */
public final class ModRegistry {
    public static final String MOD_ID = ${modClass}.MOD_ID;

    private ModRegistry() {}

    public static ResourceLocation id(String path) {
        return ${rl};
    }

    public static DeferredRegister<Item> items() {
        return DeferredRegister.create(Registries.ITEM, MOD_ID);
    }

    public static DeferredRegister<Block> blocks() {
        return DeferredRegister.create(Registries.BLOCK, MOD_ID);
    }
}
`

  return javaFile(pkg, 'ModRegistry', body)
}

// -- items -------------------------------------------------------------------

/** `Item.Properties()` for one item node, including its food and stack size. */
function itemProperties(ctx: JavaContext, node: ContentNode): string {
  const parts: string[] = ['new Item.Properties()']
  const stack = Math.round(num(node.data, 'maxStackSize', 64))
  if (stack !== 64) parts.push(`.stacksTo(${Math.max(1, Math.min(99, stack))})`)

  if (bool(node.data, 'isFood')) {
    const nutrition = Math.round(num(node.data, 'nutrition', 4))
    const saturation = num(node.data, 'saturation', 0.6)
    const method = ctx.profile.api.foodSaturationMethod
    const builder = [
      'new FoodProperties.Builder()',
      `.nutrition(${nutrition})`,
      `.${method}(${saturation}F)`,
    ]
    if (bool(node.data, 'canAlwaysEat')) builder.push('.alwaysEdible()')
    parts.push(`.food(${builder.join('')}.build())`)
  }
  if (bool(node.data, 'glint')) parts.push('.fireResistant()')
  return parts.join('')
}

function emitModItems(ctx: JavaContext, pkg: string, code: LoaderCode): VirtualFile {
  const fabric = isFabricFamily(ctx.loader)
  const items = ctx.project.nodes.filter((n) => n.kind === 'item')
  const crops = ctx.project.nodes.filter(
    (n) => n.kind === 'crop' && bool(n.data, 'generateSeed', true),
  )

  const lines: string[] = []
  const names: string[] = []

  for (const node of items) {
    const constant = constantCase(node.name)
    names.push(constant)
    lines.push(
      fabric
        ? `    public static final Supplier<Item> ${constant} =\n            ModRegistry.item(${lit(node.name)}, () -> new Item(${itemProperties(ctx, node)}));`
        : `    public static final ${code.holderType('Item', 'Item')} ${constant} =\n            REGISTER.register(${lit(node.name)}, () -> new Item(${itemProperties(ctx, node)}));`,
    )
  }

  // A crop's seed is an item on Java, not a component of the block — it has to
  // know which block it plants, so it is registered after ModBlocks is loaded.
  for (const node of crops) {
    const seedName = str(node.data, 'seedName').trim() || `${node.name}_seeds`
    const constant = constantCase(seedName)
    names.push(constant)
    const blockRef = fabric
      ? `ModBlocks.${constantCase(node.name)}.get()`
      : `ModBlocks.${constantCase(node.name)}.get()`
    lines.push(
      fabric
        ? `    public static final Supplier<Item> ${constant} =\n            ModRegistry.item(${lit(seedName)}, () -> new ItemNameBlockItem(${blockRef}, new Item.Properties()));`
        : `    public static final ${code.holderType('Item', 'Item')} ${constant} =\n            REGISTER.register(${lit(seedName)}, () -> new ItemNameBlockItem(${blockRef}, new Item.Properties()));`,
    )
  }

  const header = fabric
    ? `package ${pkg};

import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemNameBlockItem;

import java.util.function.Supplier;
`
    : `package ${pkg};

import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemNameBlockItem;
${code.registryImports.map((name) => `import ${name};`).join('\n')}

import java.util.function.Supplier;
`

  const body = `${header}
/**
 * Every item this add-on adds.
 *
 * Order matters more than it looks: a seed item holds a reference to the crop
 * block it plants, so ModBlocks has to have finished before those lines run.
 * Touching ModBlocks first in register() is what guarantees that.
 *
 * Generated by the add-on builder.
 */
public final class ModItems {
${fabric ? '' : '    public static final DeferredRegister<Item> REGISTER = ModRegistry.items();\n'}
${lines.join('\n\n') || '    // This add-on adds no items.'}

    private ModItems() {}

    public static void register() {
        // Referencing the class is enough to run its static initialiser.
    }

    public static java.util.List<${code.holderType('Item', 'Item')}> all() {
        return java.util.List.of(${names.join(', ')});
    }
}
`

  return javaFile(pkg, 'ModItems', body)
}

// -- blocks ------------------------------------------------------------------

/** `BlockBehaviour.Properties` for one block node. */
function blockProperties(node: ContentNode): string {
  const parts: string[] = ['BlockBehaviour.Properties.of()']
  const destroy = num(node.data, 'destroyTime', 1.5)
  const resistance = num(node.data, 'explosionResistance', 3)
  if (destroy < 0) parts.push('.strength(-1.0F, 3600000.0F)')
  else parts.push(`.strength(${destroy}F, ${resistance}F)`)

  const light = Math.round(num(node.data, 'lightEmission', 0))
  if (light > 0) parts.push(`.lightLevel(state -> ${Math.min(15, light)})`)

  const friction = num(node.data, 'friction', 0.6)
  if (friction !== 0.6) parts.push(`.friction(${friction}F)`)

  if (!bool(node.data, 'solid', true)) parts.push('.noCollission()')
  if (str(node.data, 'renderMethod', 'opaque') !== 'opaque') parts.push('.noOcclusion()')
  return parts.join('')
}

function emitModBlocks(ctx: JavaContext, pkg: string, stationBlocks: ContentNode[], code: LoaderCode): VirtualFile {
  const fabric = isFabricFamily(ctx.loader)
  const stationIds = new Set(stationBlocks.map((node) => node.id))
  const blocks = ctx.project.nodes.filter((n) => n.kind === 'block')
  const crops = ctx.project.nodes.filter((n) => n.kind === 'crop')

  const lines: string[] = []
  const itemised: string[] = []

  for (const node of blocks) {
    const constant = constantCase(node.name)
    const ctor = stationIds.has(node.id)
      ? `new StationBlock(${blockProperties(node)}, ${lit(node.name)})`
      : `new Block(${blockProperties(node)})`
    lines.push(
      fabric
        ? `    public static final Supplier<Block> ${constant} =\n            ModRegistry.block(${lit(node.name)}, () -> ${ctor});`
        : `    public static final ${code.holderType('Block', 'Block')} ${constant} =\n            REGISTER.register(${lit(node.name)}, () -> ${ctor});`,
    )
    itemised.push(constant)
  }

  for (const node of crops) {
    const constant = constantCase(node.name)
    const className = `${pascalCase(node.name)}CropBlock`
    lines.push(
      fabric
        ? `    public static final Supplier<Block> ${constant} =\n            ModRegistry.block(${lit(node.name)}, ${className}::new);`
        : `    public static final ${code.holderType('Block', 'Block')} ${constant} =\n            REGISTER.register(${lit(node.name)}, ${className}::new);`,
    )
    // A crop block has no block item: you plant it with its seed, exactly the
    // way wheat works, so registering one would put a stray item in creative.
  }

  const header = fabric
    ? `package ${pkg};

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.function.Supplier;
`
    : `package ${pkg};

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
${code.registryImports.map((name) => `import ${name};`).join('\n')}

import java.util.function.Supplier;
`

  const blockItems = itemised
    .map((constant) =>
      fabric
        ? `        Registry.register(BuiltInRegistries.ITEM, ModRegistry.id(${lit(
            blocks.find((n) => constantCase(n.name) === constant)!.name,
          )}), new BlockItem(${constant}.get(), new Item.Properties()));`
        : `        ModItems.REGISTER.register(${lit(
            blocks.find((n) => constantCase(n.name) === constant)!.name,
          )}, () -> new BlockItem(${constant}.get(), new Item.Properties()));`,
    )
    .join('\n')

  const body = `${header}
/**
 * Every block this add-on adds, and the item you hold in your hand for each.
 *
 * Crops are the exception and get no block item on purpose: you plant a crop
 * with its seed, so registering an item for the block itself would leave a
 * stray entry in the creative inventory that plants nothing.
 *
 * Generated by the add-on builder.
 */
public final class ModBlocks {
${fabric ? '' : '    public static final DeferredRegister<Block> REGISTER = ModRegistry.blocks();\n'}
${lines.join('\n\n') || '    // This add-on adds no blocks.'}

    private ModBlocks() {}

    public static void register() {
        registerBlockItems();
    }

    private static void registerBlockItems() {
${blockItems || '        // Nothing to give an item form.'}
    }

    public static java.util.List<${code.holderType('Block', 'Block')}> all() {
        return java.util.List.of(${[...blocks, ...crops].map((n) => constantCase(n.name)).join(', ')});
    }
}
`

  return javaFile(pkg, 'ModBlocks', body)
}

// -- crops -------------------------------------------------------------------

/**
 * One class per crop, extending vanilla's CropBlock.
 *
 * This is the clearest single example of Java being less work than Bedrock for
 * the same feature. On Bedrock a growing crop needs a scripted custom component
 * — the modern block parser dropped data-driven block events — so the builder
 * has to emit JavaScript and add a script module to the manifest. On Java,
 * extending CropBlock inherits random-tick growth, bonemeal, farmland
 * trampling, and the "is it ripe" check, and the class below only has to say
 * how many stages there are and which item is the seed.
 */
function emitCropBlock(pkg: string, node: ContentNode): VirtualFile {
  const className = `${pascalCase(node.name)}CropBlock`
  const stages = Math.max(2, Math.round(num(node.data, 'stages', 4)))
  const maxAge = stages - 1
  const seedName = str(node.data, 'seedName').trim() || `${node.name}_seeds`

  const body = `package ${pkg};

import com.mojang.serialization.MapCodec;
import net.minecraft.world.item.ItemLike;
import net.minecraft.world.level.block.CropBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.IntegerProperty;

/**
 * ${node.displayName} — ${stages} growth stages, ages 0 to ${maxAge}.
 *
 * Growth, bonemeal and the drop table all come from CropBlock. The only things
 * this class states are the stage count and the seed item.
 *
 * Generated by the add-on builder.
 */
public class ${className} extends CropBlock {
    public static final int MAX_AGE = ${maxAge};
    public static final IntegerProperty AGE = IntegerProperty.create("age", 0, MAX_AGE);

    public ${className}() {
        super(BlockBehaviour.Properties.of()
                .noCollission()
                .randomTicks()
                .instabreak()
                .sound(SoundType.CROP)
                .pushReaction(net.minecraft.world.level.material.PushReaction.DESTROY));
    }

    @Override
    public IntegerProperty getAgeProperty() {
        return AGE;
    }

    @Override
    public int getMaxAge() {
        return MAX_AGE;
    }

    @Override
    protected ItemLike getBaseSeedId() {
        return ModItems.${constantCase(seedName)}.get();
    }

    @Override
    protected MapCodec<? extends CropBlock> codec() {
        return simpleCodec(properties -> new ${className}());
    }

    @Override
    protected void createBlockStateDefinition(net.minecraft.world.level.block.state.StateDefinition.Builder<net.minecraft.world.level.block.Block, net.minecraft.world.level.block.state.BlockState> builder) {
        builder.add(AGE);
    }
}
`
  return javaFile(pkg, className, body)
}

// -- creative tab ------------------------------------------------------------

function emitCreativeTab(ctx: JavaContext, pkg: string, code: LoaderCode): VirtualFile {
  const fabric = isFabricFamily(ctx.loader)
  const first = ctx.project.nodes.find((n) => n.kind === 'item' || n.kind === 'block')
  const icon = first
    ? first.kind === 'item'
      ? `ModItems.${constantCase(first.name)}.get()`
      : `ModBlocks.${constantCase(first.name)}.get().asItem()`
    : 'net.minecraft.world.item.Items.WHEAT'

  const rl = ctx.profile.api.resourceLocation('ModRegistry.MOD_ID', '"main"')

  const body = fabric
    ? `package ${pkg};

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;

/**
 * A single tab holding everything this add-on adds, rather than scattering the
 * content through the vanilla tabs. Bedrock has no equivalent — menu_category
 * only picks one of four fixed tabs — so this is a small thing Java simply
 * does better.
 *
 * Generated by the add-on builder.
 */
public final class ModCreativeTabs {
    public static final CreativeModeTab MAIN = CreativeModeTab.builder()
            .title(Component.translatable("itemGroup." + ModRegistry.MOD_ID + ".main"))
            .icon(() -> new ItemStack(${icon}))
            .displayItems((parameters, output) -> {
                ModItems.all().forEach(item -> output.accept(item.get()));
                ModBlocks.all().forEach(block -> {
                    ItemStack stack = new ItemStack(block.get());
                    if (!stack.isEmpty()) output.accept(stack);
                });
            })
            .build();

    private ModCreativeTabs() {}

    public static void register() {
        Registry.register(BuiltInRegistries.CREATIVE_MODE_TAB, ${rl}, MAIN);
    }
}
`
    : `package ${pkg};

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
${code.registryImports.map((name) => `import ${name};`).join('\n')}

/**
 * A single tab holding everything this add-on adds, rather than scattering the
 * content through the vanilla tabs. Bedrock has no equivalent — menu_category
 * only picks one of four fixed tabs — so this is a small thing Java simply
 * does better.
 *
 * Generated by the add-on builder.
 */
public final class ModCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> REGISTER =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, ModRegistry.MOD_ID);

    public static final ${code.holderType('CreativeModeTab', 'CreativeModeTab')} MAIN =
            REGISTER.register("main", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup." + ModRegistry.MOD_ID + ".main"))
                    .icon(() -> new ItemStack(${icon}))
                    .displayItems((parameters, output) -> {
                        ModItems.all().forEach(item -> output.accept(item.get()));
                        ModBlocks.all().forEach(block -> {
                            ItemStack stack = new ItemStack(block.get());
                            if (!stack.isEmpty()) output.accept(stack);
                        });
                    })
                    .build());

    private ModCreativeTabs() {}

    public static void register() {
        // Attached to the mod bus in the main class.
    }
}
`

  return javaFile(pkg, 'ModCreativeTabs', body)
}

// -- structures --------------------------------------------------------------

/**
 * The painted structure grid, baked into a Feature class.
 *
 * Java normally places a structure from a binary `.nbt` file written by the
 * in-game structure block, which this builder has no way to produce. Placing
 * the blocks from code sidesteps the format entirely, and for the small
 * hand-painted structures the builder makes, the array below is smaller than
 * the NBT would have been.
 */
function emitStructureFeature(ctx: JavaContext, pkg: string, nodes: ContentNode[]): VirtualFile {
  const entries = nodes.map((node) => {
    const grid = node.data.grid as { size?: number[]; cells?: unknown[] } | undefined
    const size = Array.isArray(grid?.size) ? grid!.size! : [1, 1, 1]
    const cells = Array.isArray(grid?.cells) ? grid!.cells! : []
    const blocks = cells
      .map((cell) => (typeof cell === 'string' ? cell.trim() : ''))
      .map((cell) => (cell ? lit(cell) : 'null'))
    return `        LAYOUTS.put(${lit(node.name)}, new Layout(${size[0]}, ${size[1]}, ${size[2]}, new String[]{\n                ${blocks.join(', ')}\n        }));`
  })

  const body = `package ${pkg};

import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.WorldGenLevel;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Painted structures, placed block by block from a baked layout.
 *
 * The array is in the same order the painter uses: X fastest, then Z, then Y,
 * so index = (y * depth + z) * width + x. Getting that order wrong produces a
 * structure that is subtly transposed and very hard to diagnose, which is why
 * it is stated here rather than left implicit.
 *
 * Generated by the add-on builder.
 */
public final class ModStructures {
    public record Layout(int width, int height, int depth, String[] blocks) {}

    public static final Map<String, Layout> LAYOUTS = new LinkedHashMap<>();

    static {
${entries.join('\n')}
    }

    private ModStructures() {}

    public static void register() {
        // Nothing to register: the layouts are placed by place() below, which
        // your own feature or command can call.
    }

    /** Places one layout with its north-west-bottom corner at {@code origin}. */
    public static void place(WorldGenLevel level, BlockPos origin, String name) {
        Layout layout = LAYOUTS.get(name);
        if (layout == null) return;

        for (int y = 0; y < layout.height(); y++) {
            for (int z = 0; z < layout.depth(); z++) {
                for (int x = 0; x < layout.width(); x++) {
                    String id = layout.blocks()[(y * layout.depth() + z) * layout.width() + x];
                    if (id == null) continue;
                    BlockState state = stateOf(id);
                    if (state == null) continue;
                    level.setBlock(origin.offset(x, y, z), state, 3);
                }
            }
        }
    }

    private static BlockState stateOf(String id) {
        ResourceLocation key = ${ctx.profile.api.parseResourceLocation('id')};
        Block block = BuiltInRegistries.BLOCK.get(key);
        return block == Blocks.AIR ? null : block.defaultBlockState();
    }
}
`

  return javaFile(pkg, 'ModStructures', body)
}

// -- Fabric world generation --------------------------------------------------

/**
 * Attaching features to existing biomes, Fabric flavour.
 *
 * Forge and NeoForge both read a `biome_modifier` JSON file from the data pack,
 * so they need no code for this at all. Fabric has no such file and does it
 * from `BiomeModifications`, which is what this class is for. A plain data pack
 * has neither, which is why the capability matrix calls scattering "partial"
 * on that route.
 */
function emitFabricWorldgen(ctx: JavaContext, pkg: string): VirtualFile {
  const placements = ctx.project.nodes.filter(
    (node) =>
      (node.kind === 'scatter' || node.kind === 'tree') && bool(node.data, 'worldPlace', true),
  )

  const registrations = placements
    .map((node) => {
      const tags = [...list(node.data, 'biomeTags'), ...list(node.data, 'biomeTagsCustom')]
      const selector =
        tags.length === 0 || tags.includes('overworld')
          ? 'BiomeSelectors.foundInOverworld()'
          : `BiomeSelectors.tag(TagKey.create(Registries.BIOME, ResourceLocation.parse("minecraft:is_${tags[0]}")))`
      return `        BiomeModifications.addFeature(
                ${selector},
                GenerationStep.Decoration.VEGETAL_DECORATION,
                ResourceKey.create(Registries.PLACED_FEATURE, ModRegistry.id(${lit(node.name)})));`
    })
    .join('\n\n')

  const body = `package ${pkg};

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.levelgen.GenerationStep;

/**
 * Fabric has no data-driven biome modifier, so the placed features written into
 * the data pack are attached to biomes here instead.
 *
 * Generated by the add-on builder.
 */
public final class ModWorldgen {
    private ModWorldgen() {}

    public static void register() {
${registrations || '        // This add-on places nothing in the world.'}
    }
}
`

  return javaFile(pkg, 'ModWorldgen', body)
}
